config {
  type: 'operations',
  schema: 'sales_sample_output',
  name: 'order',
  description: '注文一覧（店頭とECを統合）',
  hasOutput: true,
  tags: ['01_clensing_from_outer_tables']
}

-- (1/3) 初回の場合、累積テーブルを作成
CREATE TABLE IF NOT EXISTS `sales_sample_output.order` (
  unified_order_id STRING OPTIONS(description='統合注文ID'),
  create_date DATE OPTIONS(description='日付'),
  create_datetime DATETIME OPTIONS(description='日時'),
  customer_id STRING OPTIONS(description='顧客ID'),
  price INT64 OPTIONS(description='価格'),
  price_before_discount INT64 OPTIONS(description='値引き前価格'),
  total_discount INT64 OPTIONS(description='値引き額合計'),
  total_line_discount INT64 OPTIONS(description='明細値引き額合計'),
  order_discount INT64 OPTIONS(description='注文値引き額'),
  sales_channel STRING OPTIONS(description='販売チャネル')
)
PARTITION BY create_date
OPTIONS (
  description = '注文一覧'
);

-- (2/3) 更新期間内の差分テーブルを作成
CREATE OR REPLACE TABLE `sales_sample_intermediate.order_incremental` AS (
  -- 店頭データを生成
  SELECT
    CONCAT('S_',receipt_id) AS unified_order_id,
    create_date,
    NULL AS create_datetime,
    customer_id,
    price,
    price_before_discount,
    total_discount,
    total_line_discount,
    order_discount,
    '店頭' AS sales_channel
  FROM
    ${ref('shop_order')}
  WHERE
    create_date ${dataform.projectConfig.vars.EQUALS_CALC_DATETIME}
  
  -- ECデータを結合
  UNION ALL
  SELECT
    CONCAT('E_',order_id) AS unified_order_id,
    DATE(created_at) AS create_date,
    created_at AS create_datetime,
    customer_id,
    price,
    price_before_discount,
    total_discount,
    total_line_discount,
    order_discount,
    'EC' AS sales_channel
  FROM
    ${ref('ec_order')}
  WHERE
    created_at ${dataform.projectConfig.vars.EQUALS_CALC_DATETIME}

  -- マージした後にソート
  ORDER BY create_date ASC, customer_id ASC
);

-- (3/3) 差分テーブルを累積テーブルにマージ
MERGE `sales_sample_output.order` AS t
  USING `sales_sample_intermediate.order_incremental` AS s
  ON t.unified_order_id = s.unified_order_id
WHEN NOT MATCHED BY SOURCE
  AND t.create_date ${dataform.projectConfig.vars.EQUALS_CALC_DATETIME} THEN
  DELETE
WHEN MATCHED THEN
  UPDATE SET
    t.create_date           = s.create_date,
    t.create_datetime       = s.create_datetime,
    t.customer_id           = s.customer_id,
    t.price                 = s.price,
    t.price_before_discount = s.price_before_discount,
    t.total_discount        = s.total_discount,
    t.total_line_discount   = s.total_line_discount,
    t.order_discount        = s.order_discount,
    t.sales_channel         = s.sales_channel
WHEN NOT MATCHED THEN
  INSERT (
    unified_order_id,
    create_date,
    create_datetime,
    customer_id,
    price,
    price_before_discount,
    total_discount,
    total_line_discount,
    order_discount,
    sales_channel
  )
  VALUES (
    s.unified_order_id,
    s.create_date,
    s.create_datetime,
    s.customer_id,
    s.price,
    s.price_before_discount,
    s.total_discount,
    s.total_line_discount,
    s.order_discount,
    s.sales_channel
);

