config {
  type: 'operations',
  schema: 'sales_sample_output',
  name: 'shop_order',
  description: '店頭注文一覧',
  hasOutput: true,
  tags: ['01_clensing_from_outer_tables']
}

-- (1/3) 初回の場合、累積テーブルを作成
CREATE TABLE IF NOT EXISTS `sales_sample_output.shop_order` (
  receipt_id STRING OPTIONS(description='レシートID'),
  create_date DATE OPTIONS(description='日付'),
  customer_id STRING OPTIONS(description='顧客ID'),
  price INT64 OPTIONS(description='価格'),
  price_before_discount INT64 OPTIONS(description='値引き前価格'),
  total_discount INT64 OPTIONS(description='値引き額合計'),
  total_line_discount INT64 OPTIONS(description='明細値引き額合計'),
  order_discount INT64 OPTIONS(description='注文値引き額')
)
PARTITION BY create_date
OPTIONS (
  description = '店頭注文一覧'
);

-- (2/3) 更新期間内の差分テーブルを作成
CREATE OR REPLACE TABLE `sales_sample_intermediate.shop_order_incremental` AS (
  SELECT
    receipt_id,
    MAX(create_date) AS create_date,
    MAX(customer_id) AS customer_id,
    SUM(line_price) AS price,
    SUM(line_price_before_discount) AS price_before_discount,
    SUM(line_discount) AS total_discount,
    SUM(line_discount) AS total_line_discount,
    0 AS order_discount
  FROM
    ${ref('shop_order_line_with_discount')}
  WHERE
    create_date ${dataform.projectConfig.vars.EQUALS_CALC_DATETIME}
  GROUP BY
    receipt_id
  ORDER BY
    receipt_id ASC
);

-- (3/3) 差分テーブルを累積テーブルにマージ
MERGE `sales_sample_output.shop_order` AS t
  USING `sales_sample_intermediate.shop_order_incremental` AS s
  ON t.receipt_id = s.receipt_id
WHEN NOT MATCHED BY SOURCE
  AND t.create_date ${dataform.projectConfig.vars.EQUALS_CALC_DATETIME} THEN
  DELETE
WHEN MATCHED THEN
  UPDATE SET
    t.create_date           = s.create_date,
    t.customer_id           = s.customer_id,
    t.price                 = s.price,
    t.price_before_discount = s.price_before_discount,
    t.total_discount        = s.total_discount,
    t.total_line_discount   = s.total_line_discount,
    t.order_discount        = s.order_discount
WHEN NOT MATCHED THEN
  INSERT (
    receipt_id,
    create_date,
    customer_id,
    price,
    price_before_discount,
    total_discount,
    total_line_discount,
    order_discount
  )
  VALUES (
    s.receipt_id,
    s.create_date,
    s.customer_id,
    s.price,
    s.price_before_discount,
    s.total_discount,
    s.total_line_discount,
    s.order_discount
);

